name: restaurant_project
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.8.1
  shared_preferences: ^0.5.7+2


  google_fonts: ^1.1.2
  http: ^0.12.2
  dio: ^3.0.10
  mime: ^1.0.0
  path: ^1.8.0
  file: ^6.1.1
  image_picker: ^0.6.7+1
  bloc_pattern :
  rxdart :
  flutter_spinkit: ^4.1.2
  provider: ^5.0.0
  flutter_datetime_picker: ^1.5.1
  date_format: ^2.0.2
  intl: ^0.17.0
  flutter_rating_bar: ^4.0.0
  time_range: ^1.0.2
  lite_rolling_switch: ^0.1.1
  image_utils_class: ^1.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:

 
  uses-material-design: true
  assets:
    - assets/images/222.jpg
    - assets/images/bg1.jpg
    - assets/images/bg2.jpg
    - assets/images/bg3.jpg
    - assets/images/111.png
    - assets/images/profile.jpg
    - assets/images/bgdrawer.jpg
    - assets/images/camera.png
    - assets/images/logohome.png
    - assets/images/logohome1.png
    - assets/images/food1.png
    - assets/images/food2.png
    - assets/images/food3.png
    - assets/images/food4.png
    - assets/images/food5.png
    - assets/images/food6.png
    - assets/images/food7.png
    - assets/images/food8.png
    - assets/images/food9.png
    - assets/images/food10.png
    - assets/images/p1.jpg
    - assets/icon/login.png
    - assets/icon/profile_default.png
    - assets/images/bg_default.jpg
    - assets/icon/user1.png
    - assets/icon/user2.png

  